# Generated by Django 3.2 on 2021-04-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='switch_panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_state1', models.BooleanField()),
                ('switch_state2', models.BooleanField()),
                ('switch_state3', models.BooleanField()),
                ('switch_state4', models.BooleanField()),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.switch_panel')),
            ],
        ),
    ]
