# Generated by Django 3.2 on 2021-04-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='panel',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='switch_state2',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='switch_state3',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='switch_state4',
        ),
        migrations.DeleteModel(
            name='switch_panel',
        ),
    ]
